wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
adam_epsilon:
  desc: null
  value: 1.0e-08
best_model_dir:
  desc: null
  value: outputs/best_model
cache_dir:
  desc: null
  value: cache_dir/
config:
  desc: null
  value: {}
do_lower_case:
  desc: null
  value: false
early_stopping_consider_epochs:
  desc: null
  value: false
early_stopping_delta:
  desc: null
  value: 0
early_stopping_metric:
  desc: null
  value: eval_loss
early_stopping_metric_minimize:
  desc: null
  value: true
early_stopping_patience:
  desc: null
  value: 3
encoding:
  desc: null
  value: null
eval_batch_size:
  desc: null
  value: 8
evaluate_during_training:
  desc: null
  value: false
evaluate_during_training_silent:
  desc: null
  value: true
evaluate_during_training_steps:
  desc: null
  value: 2000
evaluate_during_training_verbose:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
gradient_accumulation_steps:
  desc: null
  value: 1
lazy_delimiter:
  desc: null
  value: "\t"
lazy_header_row:
  desc: null
  value: true
lazy_labels_column:
  desc: null
  value: 1
lazy_text_a_column:
  desc: null
  value: null
lazy_text_b_column:
  desc: null
  value: null
lazy_text_column:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 4.0e-05
local_rank:
  desc: null
  value: -1
logging_steps:
  desc: null
  value: 50
manual_seed:
  desc: null
  value: 2
max_grad_norm:
  desc: null
  value: 1.0
max_seq_length:
  desc: null
  value: 128
model_name:
  desc: null
  value: /home/puck/anaconda3/envs/bert-rxnfp/lib/python3.6/site-packages/rxnfp/models/transformers/bert_pretrained
model_type:
  desc: null
  value: bert
multiprocessing_chunksize:
  desc: null
  value: 500
n_gpu:
  desc: null
  value: 1
no_cache:
  desc: null
  value: false
no_save:
  desc: null
  value: false
num_labels:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 5
output_dir:
  desc: null
  value: outputs/
overwrite_output_dir:
  desc: null
  value: false
process_count:
  desc: null
  value: 6
regression:
  desc: null
  value: true
reprocess_input_data:
  desc: null
  value: true
save_best_model:
  desc: null
  value: true
save_eval_checkpoints:
  desc: null
  value: true
save_model_every_epoch:
  desc: null
  value: true
save_optimizer_and_scheduler:
  desc: null
  value: true
save_steps:
  desc: null
  value: 2000
silent:
  desc: null
  value: false
sliding_window:
  desc: null
  value: false
stride:
  desc: null
  value: 0.8
tensorboard_dir:
  desc: null
  value: null
tie_value:
  desc: null
  value: 1
train_batch_size:
  desc: null
  value: 16
use_cached_eval_features:
  desc: null
  value: false
use_early_stopping:
  desc: null
  value: false
use_multiprocessing:
  desc: null
  value: true
wandb_kwargs:
  desc: null
  value:
    name: 5_epochs_16_batches_True_data_aug
wandb_project:
  desc: null
  value: lang-rxn
warmup_ratio:
  desc: null
  value: 0.06
warmup_steps:
  desc: null
  value: 80
weight_decay:
  desc: null
  value: 0
